/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package translateonwin;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Wise-SW
 */
public class SelectLanguage extends javax.swing.JDialog {

    /**
     * Creates new form SelectLanguage
     */
    private Vector<Language> vLang;
    private String[] signs;
    private Vector displayMember;
    TranslateOnWin parent;
    
    public SelectLanguage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            this.getContentPane().setBackground(new Color(245, 245, 245));
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SelectLanguage.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/translateonwin/icon/google.png")));
        initCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTransTo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbbFrom = new javax.swing.JComboBox();
        cbbTo = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Language");
        setResizable(false);

        lblTransTo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTransTo.setText("Translate To:");
        lblTransTo.setMaximumSize(new java.awt.Dimension(100, 15));
        lblTransTo.setPreferredSize(new java.awt.Dimension(100, 15));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Translate From:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 14));

        btnOK.setBackground(new java.awt.Color(245, 245, 245));
        btnOK.setText("OK");
        btnOK.setMaximumSize(new java.awt.Dimension(80, 23));
        btnOK.setMinimumSize(new java.awt.Dimension(80, 23));
        btnOK.setPreferredSize(new java.awt.Dimension(80, 23));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTransTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTransTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(parent != null){
            parent.getCbbFrom().setSelectedItem(cbbFrom.getSelectedItem());
            parent.getCbbTo().setSelectedItem(cbbTo.getSelectedItem());
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbbFrom;
    private javax.swing.JComboBox cbbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTransTo;
    // End of variables declaration//GEN-END:variables

    private final void initCombobox(){
        signs = Locale.getISOLanguages();
        vLang = new Vector<>();
        displayMember = new Vector();
        Language autoDetect = new Language("Auto Detect", "auto");
        vLang.add(autoDetect);
        for (int i = 0; i < signs.length; i++) {
            Locale locale = new Locale(signs[i]);
            String lang = locale.getDisplayLanguage();
            Language language = new Language(lang, signs[i]);
            vLang.add(language);
        }
        for (int i = 0; i < vLang.size(); i++) {
            String node = vLang.get(i).getLanguage();
            displayMember.add(node);
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(displayMember);
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(displayMember);
        
        cbbFrom.setModel(model);
        cbbFrom.setSelectedItem("Auto Detect");
        cbbTo.setModel(model2);
        cbbTo.setSelectedItem("English");
    }

    void setParent(TranslateOnWin parent) {
        this.parent = parent;
    }
}
